### ISSUE TITLE
Black wins, but white king was eaten

### ISSUE THREAD

**Issue by NightEugene** [caphindsight/TrulyQuantumChess#12]
Me and my friend are confused by this situation. If it isn't bug could you explain why black wins? 
![photo_2017-04-05_10-49-31](https://cloud.githubusercontent.com/assets/19973416/24695323/fe09f4a4-19ed-11e7-8040-caa7af642b05.jpg)

**Comment by caphindsight** [comment]
Not a bug :)
See, the white king is in the superposition of being dead and alive at the same time. This means that the game is in superposition of being still played and won already by the blacks at the same time! There's already a chance (and a quite good one) that blacks won, but it isn't decided yet.
After whites take the black king, they declare their victory *only* on the remaining piece of the superposition. A probabilistic measurement is performed at the end of the game in order to decide who won and who lost. In this particular case it turns out that the white king has been captured all along.

**Comment by NightEugene** [comment]
Thanks a lot! It's amazing :)
